### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by celikozlemw** [Robotistan/YouTube-DIY-Projeler#7]

**Comment by yaltan1** [comment]
Merhaba çalışmalarınızda kolaylıklar dilerim Arduino ide bağlantınız ile
yükleme yapabiliyor musunuz tam anlayamadım ancak ESP 8266 için aşağıdaki
linke bakarak çalışmanızı kontrol ediniz. Selamlar iyi günler dilerim.
https://randomnerdtutorials.com/how-to-install-esp8266-board-arduino-ide/

23 Nis 2023 Paz 18:42 tarihinde celikozlemw ***@***.***> şunu
yazdı:

**Comment by celikozlemw** [comment]
ESP8266 için yazılım güncelleme işlemi yaparak sorunun üstesinden geldim.Geri dönüşünüz için teşekkür ediyorum.İyi günler dilerim.

**Comment by yaltan1** [comment]
Rica ederim iyi günler. Başarı ve azim hep yanınızda olsun.

27 Nis 2023 Per 18:23 tarihinde ÖZLEM ***@***.***> şunu yazdı:
